version: '3.7'

services:
  server:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    environment:
      CONFIG: ./config/local.yaml
    volumes:
      - .:/app
    ports:
      - "8080"
    command: uvicorn user_management.app:app --host 0.0.0.0 --port 8080 --reload

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: test
    volumes:
      - .:/app
    command: python3.10 -m pytest tests

  mongodb:
    image: mongo:6.0
    ports:
      - "27017"
    volumes:
      - dbmongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: users_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root


volumes:
  dbmongodb: {}
  ipython_data_local: {}

networks:
  default:
    external: true
    name: users_network
